app/ipam/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError, NumberRange
from flask import render_template, current_app

from app.model import User


class RequestIpForm(FlaskForm):
    fqdn = StringField('FQDN (e.g. srv000000.mud.internal.co.za)', validators=[DataRequired()])
    network = SelectField('Subnet', validators=[DataRequired()],
        choices=[('10.84.0.0','DEV - 10.84.0.0'),('10.83.0.0','PRD - 10.83.0.0')])
    ipcount = IntegerField('IPs Required (max 10)', [NumberRange(min=1, max=10)],default='1')
    submit = SubmitField('Request IPs')

app/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_mail import Mail

from config import Config

bcrypt = Bcrypt()
db = SQLAlchemy()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Please log in to access this page.'
mail = Mail()
bootstrap = Bootstrap()


def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(config)

    bcrypt.init_app(app)
    login.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    bootstrap.init_app(app)

    with app.app_context():
        from app.main.routes import main
        app.register_blueprint(main)

        from app.auth.routes import auth
        app.register_blueprint(auth)

        from app.ipam.routes import ipam
        app.register_blueprint(ipam)

        return app

from app import model

app/ipam/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_user, logout_user, current_user

from app import bcrypt, db
from app.ipam.forms import RequestIpForm
from app.ipam.ipamdata import IpamRegister, IpamLogin, AddressCheckout, IpamConnect

from flask import Blueprint, render_template
from flask_login import login_required

ipam = Blueprint('ipam', __name__)


@ipam.route('/ipam', methods=['GET', 'POST'])
@login_required
def index():
    
    ipamconnect = IpamConnect(current_user)
    if ipamconnect['status'] == 'success':
        ipam_token = ipamconnect['data']['token']
        flash(ipamconnect['message'], category='info')
        
        form = RequestIpForm(request.form)
        if form.validate_on_submit():
            fqdn = str(form.fqdn.data).lower()
            network = form.network.data
            ipcount = form.ipcount.data

            ipRequest = {
                'network': network, 
                'fqdn': fqdn,
                'ipcount': ipcount,
                'ipam_token': ipam_token
            }
            result = AddressCheckout(ipRequest)

            flash('Successfully requested IP Addresses '+ str(result), category='info')
    else:
        
        flash(ipamconnect['data']['error'], category='danger')

    return render_template('ipam/index.html',form=form)

app/main/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/index')
@login_required
def index():
    return render_template('main/index.html')


@main.route('/profile')
@login_required
def profile():
    return render_template('main/profile.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}
  {% if title %}
    {{ title }}
  {% else %}
    Platform Services Portal
  {% endif %}
{% endblock %}

{% block navbar %}
  {% include 'includes/_navbar.html' %}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    {% block app_content %}
    {% endblock %}
  </div>
{% endblock %}

app/templates/bootstrap/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- My Style -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

app/templates/bootstrap/wtf.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group{% if required %} required{% endif %}">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# deal with jinja scoping issues? #}
  {% set field_kwargs = kwargs %}

  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'),
            **field_kwargs)}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {%- if field.flags.required %} required{% endif -%}">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {% if field.type == 'FileField' %}
            {{field(**kwargs)|safe}}
          {% else %}
            {{field(class="form-control", **kwargs)|safe}}
          {% endif %}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
              <p class="text-danger">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="text-danger">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="") %}
{#-
action="" is what we want, from http://www.ietf.org/rfc/rfc2396.txt:

4.2. Same-document References

   A URI reference that does not contain a URI is a reference to the
   current document.  In other words, an empty URI reference within a
   document is interpreted as a reference to the start of that document,
   and a reference containing only a fragment identifier is a reference
   to the identified fragment of that document.  Traversal of such a
   reference should not result in an additional retrieval action.
   However, if the URI reference occurs in a context that is always
   intended to result in a new request, as in the case of HTML's FORM
   element, then an empty URI reference represents the base URI of the
   current document and should be replaced by that URI when transformed
   into a request.

 -#}
{#- if any file fields are inside the form and enctype is automatic, adjust
    if file fields are found. could really use the equalto test of jinja2
    here, but latter is not available until 2.8

    warning: the code below is guaranteed to make you cry =(
#}
{%- set _enctype = [] %}
{%- if enctype is none -%}
  {%- for field in form %}
    {%- if field.type == 'FileField' %}
      {#- for loops come with a fairly watertight scope, so this list-hack is
          used to be able to set values outside of it #}
      {%- set _ = _enctype.append('multipart/form-data') -%}
    {%- endif %}
  {%- endfor %}
{%- else %}
  {% set _ = _enctype.append(enctype) %}
{%- endif %}
<form
  {%- if action != None %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if _enctype[0] %} enctype="{{_enctype[0]}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}

app/templates/includes/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    {% for category, message in messages %}
      {% if category == 'message' %}
        <div class="alert alert-{{ category }}">{{ message }}</div>
      {% else %}
        <div class="alert alert-info">{{ message }}</div>
      {% endif %}
    {% endfor %}
  {% endif %}
{%- endwith %}

app/templates/includes/_navbar.html
<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #274e68;">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">PS PORTAL</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="navbar-nav mr-auto">
        {% if current_user.is_authenticated %}        
        <li class="nav-item {% if request.path == url_for('main.index') %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
        </li>
        <li class="nav-item {% if request.path == url_for('ipam.index') %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('ipam.index') }}">IPAM</a>
        </li>        
        {% endif %}        
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.profile') }}">{{ current_user.firstname }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
        </li>        
        {% else %}
        <li class="nav-item {% if request.path == url_for('auth.login') %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        <li class="nav-item {% if request.path == url_for('auth.register') %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

app/templates/ipam/index.html
{% extends 'base.html' %}

{% block app_content %}
  
  <div class="row justify-content-center">
    <div class="col-md-6">
      {% include 'includes/_messages.html' %}
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1>IPAM Dashboard</h1>
      <p>Request and Review IP Addresses for the ACI Network.</p>

      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">{{ legend }}</legend>
          <div class="form-group">
            {{ form.network.label(class="form-control-label") }}
            {% if form.network.errors %}
              {{ form.network(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.network.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.network(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.fqdn.label(class="form-control-label") }}
            {% if form.fqdn.errors %}
              {{ form.fqdn(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.fqdn.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.fqdn(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.ipcount.label(class="form-control-label") }}
            {% if form.ipcount.errors %}
              {{ form.ipcount(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.ipcount.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.ipcount(class="form-control form-control-lg") }}
            {% endif %}
          </div>          
        </fieldset>
        <hr>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>

  </div>  

{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% block app_content %}
  <h1>Hi, {{ current_user.firstname }}</h1>
  <hr>
  <p>You can use the IPAM page to request new ip addresses on the ACI network.</p>
{% endblock %}

app/templates/main/profile.html
{% extends 'base.html' %}
{% block app_content %}
  <h1>Hello {{ current_user.firstname }}!</h1>
  
  <div class="table-responsive">
    <table class="table">
      <tr>
        <th style="width:30%">MUD ID</th>
        <td>{{ current_user.username }}</td>
      </tr>
      <tr>
        <th>Last Logon</th>
        <td>{{ current_user.lastlogon }}</td>
      </tr>          
      <tr>
        <th>Email</th>
        <td>{{ current_user.email }}</td>
      </tr>
      <tr>
        <th>Firstname</th>
        <td>{{ current_user.firstname }}</td>
      </tr>
      <tr>
        <th>Surname</th>
        <td>{{ current_user.surname }}</td>
      </tr>
      <tr>
        <th>Mobile</th>
        <td>{{ current_user.mobile }}</td>
      </tr>
      <tr>
        <th>Joined</th>
        <td>{{ current_user.created }}</td>
      </tr>            
    </table>
  </div>
  <hr>

{% endblock %}